name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - name: Install Dependencies
      run: npm run render-build

    - name: Deploy to Render
      run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
      env:
        NODE_ENV: production