name: Run Cypress Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          node_modules
          */node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Install Dependencies
      run: npm run install

    - name: Build Server
      run: cd server && npm run build

    - name: Start Development Servers
      run: npm run develop &
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        NODE_ENV: test

    - name: Wait for Servers
      run: |
        npx wait-on --timeout 60000 http://localhost:3000
        npx wait-on --timeout 60000 http://localhost:5173

    - name: Run Cypress Tests
      run: npm run test
      env:
        CYPRESS_BASE_URL: http://localhost:5173